[CmdletBinding(PositionalBinding = $false)]
param(
    [Parameter(Mandatory = $true)]
    [string[]]$Lang,

    [Parameter()]
    [string]$OutputName
)

$runtime = $global:GlobalConfig.runtime 
$Path = $runtime.WorkDir

$targetDir = $Path
if (Test-Path -LiteralPath $Path -PathType Leaf) {
    $targetDir = Split-Path -Path $Path -Parent
}

$allFiles = Get-ChildItem -Path $targetDir -Filter "*.srt" -File

if ($allFiles.Count -eq 0) {
    Write-LogMessage "在 $targetDir 没有找到任何 SRT 文件。" -Level Warning
    return
}

# 搜寻所有前缀 baseName
$baseNames = @()
foreach ($file in $allFiles) {
    foreach ($l in $Lang) {
        $escL = [regex]::Escape($l)
        $pattern = "^(.+?)[\.\-]$escL\.srt$"
        if ($file.Name -match $pattern) {
            $baseName = $matches[1]
            if ($baseNames -notcontains $baseName) {
                $baseNames += $baseName
            }
        }
    }
}

if ($baseNames.Count -eq 0) {
    Write-LogMessage "未发现满足指定语言数组规则的字幕文件 ..." -Level Warning
    return
}

# 辅助函数：解析 SRT
function Parse-Srt {
    param([string]$FilePath, [string]$LangTag)
    
    if (-not (Test-Path -LiteralPath $FilePath)) { return @() }
    
    $content = Get-Content $FilePath -Raw -Encoding UTF8
    # 统一换行符并按空行分割块
    $blocks = $content -split '\r?\n\s*\r?\n'
    $items = @()
    
    foreach ($block in $blocks) {
        $lines = $block -split '\r?\n' | Where-Object { $_.Trim() -ne "" }
        # 寻找匹配时间轴的行
        $timeLineIndex = -1
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match '(\d{1,2}:\d{2}:\d{2}[,\.]\d{3})\s*-->\s*(\d{1,2}:\d{2}:\d{2}[,\.]\d{3})') {
                $timeLineIndex = $i
                break
            }
        }
        
        if ($timeLineIndex -ne -1 -and ($timeLineIndex + 1) -lt $lines.Count) {
            $startStr = $matches[1].Replace(',', '.')
            $endStr = $matches[2].Replace(',', '.')
            
            try {
                $start = [TimeSpan]::Parse($startStr)
                $end = [TimeSpan]::Parse($endStr)
                $textLines = $lines[($timeLineIndex + 1)..($lines.Count - 1)]
                
                $items += [PSCustomObject]@{
                    Lang  = $LangTag
                    Start = $start
                    End   = $end
                    Text  = $textLines -join '\N'
                }
            } catch {
                # 解析失败则跳过该块
            }
        }
    }
    return $items
}

# 辅助函数：SRT 时间转 ASS 时间 (H:MM:SS.CC)
function Convert-SrtToAssTime {
    param([TimeSpan]$ts)
    $h = [int][math]::Floor($ts.TotalHours)
    $m = [int]$ts.Minutes
    $s = [int]$ts.Seconds
    $c = [int][math]::Floor($ts.Milliseconds / 10)
    return "{0}:{1:D2}:{2:D2}.{3:D2}" -f $h, $m, $s, $c
}

foreach ($baseName in $baseNames) {
    Write-LogMessage -NoPrefix "========================================="
    Write-LogMessage "正在生成 ASS 联合字幕: $baseName" -Level Info
    
    $assLines = New-Object System.Collections.Generic.List[string]
    
    # Header
    $assLines.Add("[Script Info]")
    $assLines.Add("; Script generated by srt-join-ass.ps1")
    $assLines.Add("ScriptType: v4.00+")
    $assLines.Add("PlayResX: 1920")
    $assLines.Add("PlayResY: 1080")
    $assLines.Add("ScaledBorderAndShadow: yes")
    $assLines.Add("")
    
    # Styles
    $assLines.Add("[V4+ Styles]")
    $assLines.Add("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding")
    # Primary: 白色，较大，靠下
    $assLines.Add("Style: Primary,Microsoft YaHei,54,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,35,1")
    # Secondary: 浅灰色，较小，稍微靠上
    $assLines.Add("Style: Secondary,Arial,38,&H00D3D3D3,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1.5,1,2,10,10,95,1")
    $assLines.Add("")
    
    # Events
    $assLines.Add("[Events]")
    $assLines.Add("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text")
    
    $allSubtitleCollections = @()
    for ($i = 0; $i -lt $Lang.Count; $i++) {
        $l = $Lang[$i]
        
        $path1 = Join-Path -Path $targetDir -ChildPath "$baseName.$l.srt"
        $path2 = Join-Path -Path $targetDir -ChildPath "$baseName-$l.srt"
        $targetFile = if (Test-Path -LiteralPath $path1) { $path1 } else { $path2 }
        
        if (Test-Path -LiteralPath $targetFile) {
            $items = Parse-Srt -FilePath $targetFile -LangTag $l
            if ($items.Count -gt 0) {
                $allSubtitleCollections += @{ LangIndex = $i; Items = $items; Lang = $l }
            }
        }
    }
    
    if ($allSubtitleCollections.Count -eq 0) {
        Write-LogMessage "  -> 未找到任何匹配的字幕文件，跳过。" -Level Warning
        continue
    }

    # 简单 Dump 模式：保持原汁原味的时间轴，不切碎
    foreach ($coll in $allSubtitleCollections) {
        $style = if ($coll.LangIndex -eq 0) { "Primary" } else { "Secondary" }
        Write-LogMessage "  -> 处理语言: $($coll.Lang) (使用样式: $style)" -Level Info
        foreach ($item in $coll.Items) {
            $startAss = Convert-SrtToAssTime -ts $item.Start
            $endAss   = Convert-SrtToAssTime -ts $item.End
            # 过滤 HTML 标签并处理换行
            $cleanText = $item.Text -replace '<[^>]+>', ''
            $assLines.Add("Dialogue: 0,$startAss,$endAss,$style,,0,0,0,,$cleanText")
        }
    }
    
    $outFileName = if ($OutputName) { "$OutputName.ass" } else { "$baseName.ass" }
    $outFilePath = Join-Path -Path $targetDir -ChildPath $outFileName
    
    # 使用 UTF-8 带 BOM 写入，确保更好的兼容性
    [System.IO.File]::WriteAllLines($outFilePath, $assLines.ToArray(), [System.Text.Encoding]::UTF8)
    
    Write-LogMessage "  -> 已保存至 ASS 文件: $outFileName" -Level Success
}
